----------------

```{admonition} Learning Objectives
- Handle missing values in raster data using rioxarray
- Set and modify nodata values for masking operations
- Replace and update pixel values using xarray operations
- Apply mathematical transformations to raster data

----------------

# Editing Rasters and Remotely Sensed Data with Rioxarray


## Masking Out Values with where()

The `xarray.DataArray.where()` function provides a powerful way to mask data by replacing unwanted values with NaN. This is particularly useful for handling invalid pixels or outliers in remotely sensed data.

In [1]:
import rioxarray as rxr
import numpy as np

image_path = "../../pygis/data/LC08_L1TP_224078_20200518_20200518_01_RT.TIF"

# Zeros are replaced with nans
src = rxr.open_rasterio(image_path)
data = src.where(src != 0)

## Setting nodata Values with rioxarray  
Setting missing data values in raster files can be accomplished using rioxarray's `rio.write_nodata()` method. This is essential when the raster file doesn't have proper nodata values set in its metadata.

In [2]:
import rioxarray as rxr
import numpy as np

image_path = "../../pygis/data/LC08_L1TP_224078_20200518_20200518_01_RT.TIF"

# Set nodata=0 and mask
src = rxr.open_rasterio(image_path).rio.write_nodata(0)
print('nodata value:', src.rio.nodata)

# Replace 0 with nan (equivalent to mask_nodata)
src = src.where(src != 0, np.nan)

nodata value: 0


## Rescaling Pixel Values 
Most remotely sensed data is stored as integer values to minimize storage space. We often need to rescale these values back to meaningful physical units (like reflectance values between 0-1). This can be done through simple arithmetic operations with rioxarray DataArrays.

In [3]:
import rioxarray as rxr

image_path = "../../pygis/data/LC08_L1TP_224078_20200518_20200518_01_RT.TIF"

# Apply scale factor of 0.0001
src = rxr.open_rasterio(image_path)
src_scaled = src * 0.0001
print("Scale factor applied: 0.0001")

Scale factor applied: 0.0001


 
## Replacing Specific Values

The `xarray.where()` function provides flexible value replacement capabilities, similar to `pandas.DataFrame.replace()`. You can use conditional logic to replace specific pixel values with new ones.

In [4]:
import rioxarray as rxr
import xarray as xr

image_path = "../../pygis/data/LC08_L1TP_224078_20200518_20200518_01_RT.TIF"

# Replace 1 with 10
src = rxr.open_rasterio(image_path)
data = xr.where(src == 1, 10, src)

```{note}    
The `xr.where()` function is particularly useful for categorical data transformations and reclassification operations.
```

## Mathematical Operations on Rasters

Rioxarray DataArrays support all standard mathematical operations including addition, subtraction, multiplication, and division. These operations are applied element-wise (pixel-by-pixel) across the entire array.

In [5]:
import rioxarray as rxr

image_path = "../../pygis/data/LC08_L1TP_224078_20200518_20200518_01_RT.TIF"

# Mathematical operation: multiply by 0.001 and add 80
src = rxr.open_rasterio(image_path)
data = src * 0.001 + 80
print(data[0].values)

[[80.    80.    80.    ... 80.    80.    80.   ]
 [80.    80.    80.    ... 80.    80.    80.   ]
 [80.    80.    80.    ... 80.    80.    80.   ]
 ...
 [87.692 87.518 87.513 ... 87.44  87.432 87.415]
 [87.586 87.59  87.61  ... 87.44  87.411 87.425]
 [87.576 87.743 87.77  ... 87.464 87.443 87.406]]
