(f_rs_edit)=


----------------

```{admonition} Learning Objectives
- Handle missing values
- Setting missing values
- Replacing values

```
```{admonition} Review
* [Opening remotely sensed data](f_rs_io.md)
```
----------------

# Editing Rasters and Remotely Sensed Data


## Masking Out Certain Values

The `xarray.DataArray.where` function masks data by setting nans, as demonstrated by the example below.

In [1]:
import rioxarray as rxr
import numpy as np

image_path = "../../pygis/data/LC08_L1TP_224078_20200518_20200518_01_RT.TIF"

# Zeros are replaced with nans
src = rxr.open_rasterio(image_path)
data = src.where(src != 0)

## Setting 'no data' Values  
Setting missing data values, when not available in the raster profile, can be done using the [configuration manager](f_rs_config.md) or as an argument in the `open` command.

In [2]:
import rioxarray as rxr
import numpy as np

image_path = "../../pygis/data/LC08_L1TP_224078_20200518_20200518_01_RT.TIF"

# Set nodata=0 and mask
src = rxr.open_rasterio(image_path).rio.write_nodata(0)
print('nodata value:', src.rio.nodata)

# Replace 0 with nan (equivalent to mask_nodata)
src = src.where(src != 0, np.nan)

nodata value: 0


## Rescaling Values 
Most remotely sensed data is stored as `int` to minimize space. We are often left to rescale the values back to floating point on the backend. This can be done in a few ways in geowombat. If the sensor you are using has a geowombat profile, please use that - refer to [configuration manager docs](f_rs_config.md). If it is not natively supported we can manually set the scaling factor using the `gw.config.update`

In [4]:
import rioxarray as rxr

image_path = "../../pygis/data/LC08_L1TP_224078_20200518_20200518_01_RT.TIF"

# Apply scale factor of 0.0001
src = rxr.open_rasterio(image_path)
src_scaled = src * 0.0001
print("Scale factor applied: 0.0001")

Scale factor applied: 0.0001


 
## Replace values

The GeoWombat `replace` function mimics `pandas.DataFrame.replace`.

In [5]:
import rioxarray as rxr
import xarray as xr

image_path = "../../pygis/data/LC08_L1TP_224078_20200518_20200518_01_RT.TIF"

# Replace 1 with 10
src = rxr.open_rasterio(image_path)
data = xr.where(src == 1, 10, src)

```{note}    
The `replace` function is typically used with categorical data.
```

## Updating Values

Geowombat also accepts normal mathematical expressions such as multiplication and addition:

In [6]:
import rioxarray as rxr

image_path = "../../pygis/data/LC08_L1TP_224078_20200518_20200518_01_RT.TIF"

# Mathematical operation: multiply by 0.001 and add 80
src = rxr.open_rasterio(image_path)
data = src * 0.001 + 80
print(data[0].values)

[[80.    80.    80.    ... 80.    80.    80.   ]
 [80.    80.    80.    ... 80.    80.    80.   ]
 [80.    80.    80.    ... 80.    80.    80.   ]
 ...
 [87.692 87.518 87.513 ... 87.44  87.432 87.415]
 [87.586 87.59  87.61  ... 87.44  87.411 87.425]
 [87.576 87.743 87.77  ... 87.464 87.443 87.406]]
